/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.schoolclass.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.rm2pt.sample.schoolclass.ide.contentassist.antlr.internal.InternalDslParser;
import org.rm2pt.sample.schoolclass.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSchoolClassAccess().getGroup(), "rule__SchoolClass__Group__0");
			builder.put(grammarAccess.getSchoolClassAccess().getGroup_4(), "rule__SchoolClass__Group_4__0");
			builder.put(grammarAccess.getSchoolClassAccess().getGroup_4_3(), "rule__SchoolClass__Group_4_3__0");
			builder.put(grammarAccess.getMentorAccess().getGroup(), "rule__Mentor__Group__0");
			builder.put(grammarAccess.getMentorAccess().getGroup_4(), "rule__Mentor__Group_4__0");
			builder.put(grammarAccess.getMentorAccess().getGroup_4_3(), "rule__Mentor__Group_4_3__0");
			builder.put(grammarAccess.getMentorAccess().getGroup_5(), "rule__Mentor__Group_5__0");
			builder.put(grammarAccess.getMentorAccess().getGroup_5_3(), "rule__Mentor__Group_5_3__0");
			builder.put(grammarAccess.getMenteeAccess().getGroup(), "rule__Mentee__Group__0");
			builder.put(grammarAccess.getMenteeAccess().getGroup_4(), "rule__Mentee__Group_4__0");
			builder.put(grammarAccess.getMenteeAccess().getGroup_4_3(), "rule__Mentee__Group_4_3__0");
			builder.put(grammarAccess.getMenteeAccess().getGroup_5(), "rule__Mentee__Group_5__0");
			builder.put(grammarAccess.getMenteeAccess().getGroup_5_3(), "rule__Mentee__Group_5_3__0");
			builder.put(grammarAccess.getSchoolClassAccess().getNameAssignment_2(), "rule__SchoolClass__NameAssignment_2");
			builder.put(grammarAccess.getSchoolClassAccess().getMembersAssignment_4_2(), "rule__SchoolClass__MembersAssignment_4_2");
			builder.put(grammarAccess.getSchoolClassAccess().getMembersAssignment_4_3_1(), "rule__SchoolClass__MembersAssignment_4_3_1");
			builder.put(grammarAccess.getMentorAccess().getNameAssignment_2(), "rule__Mentor__NameAssignment_2");
			builder.put(grammarAccess.getMentorAccess().getStudentAssignment_4_2(), "rule__Mentor__StudentAssignment_4_2");
			builder.put(grammarAccess.getMentorAccess().getStudentAssignment_4_3_1(), "rule__Mentor__StudentAssignment_4_3_1");
			builder.put(grammarAccess.getMentorAccess().getTeacherAssignment_5_2(), "rule__Mentor__TeacherAssignment_5_2");
			builder.put(grammarAccess.getMentorAccess().getTeacherAssignment_5_3_1(), "rule__Mentor__TeacherAssignment_5_3_1");
			builder.put(grammarAccess.getMenteeAccess().getNameAssignment_2(), "rule__Mentee__NameAssignment_2");
			builder.put(grammarAccess.getMenteeAccess().getStudentAssignment_4_2(), "rule__Mentee__StudentAssignment_4_2");
			builder.put(grammarAccess.getMenteeAccess().getStudentAssignment_4_3_1(), "rule__Mentee__StudentAssignment_4_3_1");
			builder.put(grammarAccess.getMenteeAccess().getTeacherAssignment_5_2(), "rule__Mentee__TeacherAssignment_5_2");
			builder.put(grammarAccess.getMenteeAccess().getTeacherAssignment_5_3_1(), "rule__Mentee__TeacherAssignment_5_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
