/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.schoolclass.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SchoolClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.schoolclass.Dsl.SchoolClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSchoolClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSchoolClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMembersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cMembersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cMembersPersonParserRuleCall_4_2_0 = (RuleCall)cMembersAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cMembersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cMembersPersonParserRuleCall_4_3_1_0 = (RuleCall)cMembersAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SchoolClass returns SchoolClass:
		//    {SchoolClass}
		//    'SchoolClass'
		//    name=EString
		//    '{'
		//        ('members' '{' members+=Person ( "," members+=Person)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SchoolClass}
		//'SchoolClass'
		//name=EString
		//'{'
		//    ('members' '{' members+=Person ( "," members+=Person)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SchoolClass}
		public Action getSchoolClassAction_0() { return cSchoolClassAction_0; }
		
		//'SchoolClass'
		public Keyword getSchoolClassKeyword_1() { return cSchoolClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('members' '{' members+=Person ( "," members+=Person)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'members'
		public Keyword getMembersKeyword_4_0() { return cMembersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//members+=Person
		public Assignment getMembersAssignment_4_2() { return cMembersAssignment_4_2; }
		
		//Person
		public RuleCall getMembersPersonParserRuleCall_4_2_0() { return cMembersPersonParserRuleCall_4_2_0; }
		
		//( "," members+=Person)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//members+=Person
		public Assignment getMembersAssignment_4_3_1() { return cMembersAssignment_4_3_1; }
		
		//Person
		public RuleCall getMembersPersonParserRuleCall_4_3_1_0() { return cMembersPersonParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.schoolclass.Dsl.Person");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMentorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMenteeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Person returns Person:
		//    Mentor | Mentee;
		@Override public ParserRule getRule() { return rule; }
		
		//Mentor | Mentee
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Mentor
		public RuleCall getMentorParserRuleCall_0() { return cMentorParserRuleCall_0; }
		
		//Mentee
		public RuleCall getMenteeParserRuleCall_1() { return cMenteeParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.schoolclass.Dsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class MentorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.schoolclass.Dsl.Mentor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMentorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMentorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStudentKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStudentAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cStudentPersonCrossReference_4_2_0 = (CrossReference)cStudentAssignment_4_2.eContents().get(0);
		private final RuleCall cStudentPersonEStringParserRuleCall_4_2_0_1 = (RuleCall)cStudentPersonCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStudentAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cStudentPersonCrossReference_4_3_1_0 = (CrossReference)cStudentAssignment_4_3_1.eContents().get(0);
		private final RuleCall cStudentPersonEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cStudentPersonCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTeacherKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cTeacherAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cTeacherPersonCrossReference_5_2_0 = (CrossReference)cTeacherAssignment_5_2.eContents().get(0);
		private final RuleCall cTeacherPersonEStringParserRuleCall_5_2_0_1 = (RuleCall)cTeacherPersonCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cTeacherAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cTeacherPersonCrossReference_5_3_1_0 = (CrossReference)cTeacherAssignment_5_3_1.eContents().get(0);
		private final RuleCall cTeacherPersonEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cTeacherPersonCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Mentor returns Mentor:
		//    {Mentor}
		//    'Mentor'
		//    name=EString
		//    '{'
		//        ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		//        ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Mentor}
		//'Mentor'
		//name=EString
		//'{'
		//    ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		//    ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Mentor}
		public Action getMentorAction_0() { return cMentorAction_0; }
		
		//'Mentor'
		public Keyword getMentorKeyword_1() { return cMentorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Student'
		public Keyword getStudentKeyword_4_0() { return cStudentKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//Student+=[Person|EString]
		public Assignment getStudentAssignment_4_2() { return cStudentAssignment_4_2; }
		
		//[Person|EString]
		public CrossReference getStudentPersonCrossReference_4_2_0() { return cStudentPersonCrossReference_4_2_0; }
		
		//EString
		public RuleCall getStudentPersonEStringParserRuleCall_4_2_0_1() { return cStudentPersonEStringParserRuleCall_4_2_0_1; }
		
		//( "," Student+=[Person|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//Student+=[Person|EString]
		public Assignment getStudentAssignment_4_3_1() { return cStudentAssignment_4_3_1; }
		
		//[Person|EString]
		public CrossReference getStudentPersonCrossReference_4_3_1_0() { return cStudentPersonCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getStudentPersonEStringParserRuleCall_4_3_1_0_1() { return cStudentPersonEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Teacher'
		public Keyword getTeacherKeyword_5_0() { return cTeacherKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//Teacher+=[Person|EString]
		public Assignment getTeacherAssignment_5_2() { return cTeacherAssignment_5_2; }
		
		//[Person|EString]
		public CrossReference getTeacherPersonCrossReference_5_2_0() { return cTeacherPersonCrossReference_5_2_0; }
		
		//EString
		public RuleCall getTeacherPersonEStringParserRuleCall_5_2_0_1() { return cTeacherPersonEStringParserRuleCall_5_2_0_1; }
		
		//( "," Teacher+=[Person|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//Teacher+=[Person|EString]
		public Assignment getTeacherAssignment_5_3_1() { return cTeacherAssignment_5_3_1; }
		
		//[Person|EString]
		public CrossReference getTeacherPersonCrossReference_5_3_1_0() { return cTeacherPersonCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getTeacherPersonEStringParserRuleCall_5_3_1_0_1() { return cTeacherPersonEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class MenteeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.schoolclass.Dsl.Mentee");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMenteeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMenteeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStudentKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStudentAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cStudentPersonCrossReference_4_2_0 = (CrossReference)cStudentAssignment_4_2.eContents().get(0);
		private final RuleCall cStudentPersonEStringParserRuleCall_4_2_0_1 = (RuleCall)cStudentPersonCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStudentAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cStudentPersonCrossReference_4_3_1_0 = (CrossReference)cStudentAssignment_4_3_1.eContents().get(0);
		private final RuleCall cStudentPersonEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cStudentPersonCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTeacherKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cTeacherAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cTeacherPersonCrossReference_5_2_0 = (CrossReference)cTeacherAssignment_5_2.eContents().get(0);
		private final RuleCall cTeacherPersonEStringParserRuleCall_5_2_0_1 = (RuleCall)cTeacherPersonCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cTeacherAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cTeacherPersonCrossReference_5_3_1_0 = (CrossReference)cTeacherAssignment_5_3_1.eContents().get(0);
		private final RuleCall cTeacherPersonEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cTeacherPersonCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Mentee returns Mentee:
		//    {Mentee}
		//    'Mentee'
		//    name=EString
		//    '{'
		//        ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		//        ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Mentee}
		//'Mentee'
		//name=EString
		//'{'
		//    ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		//    ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Mentee}
		public Action getMenteeAction_0() { return cMenteeAction_0; }
		
		//'Mentee'
		public Keyword getMenteeKeyword_1() { return cMenteeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Student'
		public Keyword getStudentKeyword_4_0() { return cStudentKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//Student+=[Person|EString]
		public Assignment getStudentAssignment_4_2() { return cStudentAssignment_4_2; }
		
		//[Person|EString]
		public CrossReference getStudentPersonCrossReference_4_2_0() { return cStudentPersonCrossReference_4_2_0; }
		
		//EString
		public RuleCall getStudentPersonEStringParserRuleCall_4_2_0_1() { return cStudentPersonEStringParserRuleCall_4_2_0_1; }
		
		//( "," Student+=[Person|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//Student+=[Person|EString]
		public Assignment getStudentAssignment_4_3_1() { return cStudentAssignment_4_3_1; }
		
		//[Person|EString]
		public CrossReference getStudentPersonCrossReference_4_3_1_0() { return cStudentPersonCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getStudentPersonEStringParserRuleCall_4_3_1_0_1() { return cStudentPersonEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Teacher'
		public Keyword getTeacherKeyword_5_0() { return cTeacherKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//Teacher+=[Person|EString]
		public Assignment getTeacherAssignment_5_2() { return cTeacherAssignment_5_2; }
		
		//[Person|EString]
		public CrossReference getTeacherPersonCrossReference_5_2_0() { return cTeacherPersonCrossReference_5_2_0; }
		
		//EString
		public RuleCall getTeacherPersonEStringParserRuleCall_5_2_0_1() { return cTeacherPersonEStringParserRuleCall_5_2_0_1; }
		
		//( "," Teacher+=[Person|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//Teacher+=[Person|EString]
		public Assignment getTeacherAssignment_5_3_1() { return cTeacherAssignment_5_3_1; }
		
		//[Person|EString]
		public CrossReference getTeacherPersonCrossReference_5_3_1_0() { return cTeacherPersonCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getTeacherPersonEStringParserRuleCall_5_3_1_0_1() { return cTeacherPersonEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final SchoolClassElements pSchoolClass;
	private final PersonElements pPerson;
	private final EStringElements pEString;
	private final MentorElements pMentor;
	private final MenteeElements pMentee;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSchoolClass = new SchoolClassElements();
		this.pPerson = new PersonElements();
		this.pEString = new EStringElements();
		this.pMentor = new MentorElements();
		this.pMentee = new MenteeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.rm2pt.sample.schoolclass.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SchoolClass returns SchoolClass:
	//    {SchoolClass}
	//    'SchoolClass'
	//    name=EString
	//    '{'
	//        ('members' '{' members+=Person ( "," members+=Person)* '}' )?
	//    '}';
	public SchoolClassElements getSchoolClassAccess() {
		return pSchoolClass;
	}
	
	public ParserRule getSchoolClassRule() {
		return getSchoolClassAccess().getRule();
	}
	
	//Person returns Person:
	//    Mentor | Mentee;
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Mentor returns Mentor:
	//    {Mentor}
	//    'Mentor'
	//    name=EString
	//    '{'
	//        ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
	//        ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
	//    '}';
	public MentorElements getMentorAccess() {
		return pMentor;
	}
	
	public ParserRule getMentorRule() {
		return getMentorAccess().getRule();
	}
	
	//Mentee returns Mentee:
	//    {Mentee}
	//    'Mentee'
	//    name=EString
	//    '{'
	//        ('Student' '(' Student+=[Person|EString] ( "," Student+=[Person|EString])* ')' )?
	//        ('Teacher' '(' Teacher+=[Person|EString] ( "," Teacher+=[Person|EString])* ')' )?
	//    '}';
	public MenteeElements getMenteeAccess() {
		return pMentee;
	}
	
	public ParserRule getMenteeRule() {
		return getMenteeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
